/**
 * Tags that are derived automatically from data sources (Yahoo Finance summary,
 * portfolio membership, …) rather than entered by the user. They are stored on
 * a separate `autoTags` field on each watchlist item and are refreshed on every
 * data refresh (and when portfolio membership changes).
 *
 * Users cannot add or remove these directly; the UI merges them with the
 * user-specified `tags` only at display/filter time.
 */

export const RECOMMENDATION_TAGS = [
  'strong_buy',
  'buy',
  'hold',
  'sell',
  'strong_sell',
] as const;

export type RecommendationTag = (typeof RECOMMENDATION_TAGS)[number];

/** Auto-tag for tickers that are also in the portfolio. */
export const PORTFOLIO_AUTO_TAG = 'portfolio';

/** Auto-tag for tickers that pay a dividend (per Yahoo summary). */
export const DIVIDEND_AUTO_TAG = 'dividend';

export const AUTO_GENERATED_TAGS: ReadonlySet<string> = new Set<string>([
  PORTFOLIO_AUTO_TAG,
  DIVIDEND_AUTO_TAG,
  ...RECOMMENDATION_TAGS,
]);

export function isAutoGeneratedTag(tag: string): boolean {
  return AUTO_GENERATED_TAGS.has(tag.trim().toLowerCase());
}

export function isRecommendationTag(tag: string): tag is RecommendationTag {
  return RECOMMENDATION_TAGS.includes(tag as RecommendationTag);
}

/** Normalize an API recommendation value (e.g. "Strong Buy", "strongbuy") to the canonical tag. */
export function normalizeRecommendationKey(
  raw: string
): RecommendationTag | null {
  const s = raw.trim().toLowerCase().replace(/\s+/g, '_');
  if (RECOMMENDATION_TAGS.includes(s as RecommendationTag)) {
    return s as RecommendationTag;
  }
  const map: Record<string, RecommendationTag> = {
    strongbuy: 'strong_buy',
    strongsell: 'strong_sell',
  };
  return map[s] ?? null;
}

export function formatRecommendation(key: string): string {
  if (!key) return '—';
  return key
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

/** Split a mixed legacy tag list into user-specified tags and auto-generated tags. */
export function splitLegacyTags(mixed: string[]): {
  tags: string[];
  autoTags: string[];
} {
  const tags: string[] = [];
  const autoTags: string[] = [];
  for (const t of mixed) {
    if (isAutoGeneratedTag(t)) autoTags.push(t);
    else tags.push(t);
  }
  return { tags, autoTags };
}
