import { useState, useEffect, useCallback, useMemo, useRef } from 'react';
import {
  Eye,
  Plus,
  X,
  Trash2,
  Tag,
  LineChart,
  Target,
  ArrowUp,
  ArrowDown,
} from 'lucide-react';
import {
  ResponsiveContainer,
  ComposedChart,
  Line,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
  ReferenceLine,
} from 'recharts';
import {
  useWatchlist,
  useWatchlistTags,
  useHoldings,
  useLatestIntrinsicValues,
  useIntrinsicValues,
  useNotes,
  addWatchlistItem,
  updateWatchlistItem,
  deleteWatchlistItem,
  addIntrinsicValue,
  deleteIntrinsicValue,
  syncPortfolioToWatchlist,
} from '../db/hooks';
import {
  fetchTickerSummaries,
  fetchHistoricalPrices,
  lookupTicker,
  clearAllCaches,
} from '../services/yahooFinance';
import type { TickerSummary, HistoricalPrice, ChartRange } from '../services/yahooFinance';
import type { IntrinsicValue } from '../types';
import { formatCurrency, cn } from '../utils/format';

const RECOMMENDATION_TAGS = ['strong_buy', 'buy', 'hold', 'sell', 'strong_sell'] as const;

/** Tags that are set automatically; users cannot add them manually when adding to watchlist. */
const AUTO_GENERATED_TAGS = new Set<string>([
  'portfolio',
  'dividend',
  ...RECOMMENDATION_TAGS,
]);

function isAutoGeneratedTag(tag: string): boolean {
  return AUTO_GENERATED_TAGS.has(tag.trim().toLowerCase());
}

function formatRecommendation(key: string): string {
  if (!key) return '—';
  return key
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join(' ');
}

function isRecommendationTag(tag: string): tag is (typeof RECOMMENDATION_TAGS)[number] {
  return RECOMMENDATION_TAGS.includes(tag as (typeof RECOMMENDATION_TAGS)[number]);
}

/** Normalize API recommendation value to our tag key (e.g. "Strong Buy" or "strong_buy" -> "strong_buy"). */
function normalizeRecommendationKey(raw: string): (typeof RECOMMENDATION_TAGS)[number] | null {
  const s = raw.trim().toLowerCase().replace(/\s+/g, '_');
  if (RECOMMENDATION_TAGS.includes(s as (typeof RECOMMENDATION_TAGS)[number]))
    return s as (typeof RECOMMENDATION_TAGS)[number];
  const map: Record<string, (typeof RECOMMENDATION_TAGS)[number]> = {
    strongbuy: 'strong_buy',
    strongsell: 'strong_sell',
  };
  return map[s] ?? null;
}
import { useMarketState } from '../hooks/useMarketState';
import { useRegisterRefresh } from '../contexts/RefreshTimerContext';
import { useExtendedHours } from '../contexts/ExtendedHoursContext';
import { EmptyState } from '../components/common/EmptyState';
import { MarketBadge } from '../components/common/MarketBadge';
import { RefreshButton } from '../components/common/RefreshButton';
import { Modal } from '../components/common/Modal';
import { TickerSearchInput } from '../components/common/TickerSearchInput';
import { TickerDetailView } from '../components/research/TickerDetailView';

export function Watchlist() {
  const items = useWatchlist();
  const holdings = useHoldings();
  const allTags = useWatchlistTags();
  const marketState = useMarketState();
  const latestIVs = useLatestIntrinsicValues();
  const [summaries, setSummaries] = useState<Map<string, TickerSummary>>(
    new Map()
  );
  const [loading, setLoading] = useState(false);
  const [activeTag, setActiveTag] = useState<string | null>(null);
  const [showAdd, setShowAdd] = useState(false);
  const [chartTicker, setChartTicker] = useState<string | null>(null);
  const [sortCol, setSortCol] = useState<'ticker' | 'price' | 'change' | 'intrinsic' | 'target' | 'min' | 'dividend'>('min');
  const [sortDir, setSortDir] = useState<'asc' | 'desc'>('desc');

  // Re-run portfolio sync whenever holdings change so "portfolio" tag stays correct
  const holdingsKey = useMemo(
    () => holdings.map((h) => h.ticker).join(','),
    [holdings]
  );
  useEffect(() => {
    syncPortfolioToWatchlist();
  }, [holdingsKey]);

  const tickerKey = items.map((w) => w.ticker).join(',');

  const fetchAll = useCallback(async () => {
    const tickers = tickerKey ? tickerKey.split(',') : [];
    if (tickers.length === 0) {
      setSummaries(new Map());
      return;
    }
    setLoading(true);
    try {
      await clearAllCaches();
      setSummaries(await fetchTickerSummaries(tickers));
    } finally {
      setLoading(false);
    }
  }, [tickerKey]);

  useEffect(() => {
    const tickers = tickerKey ? tickerKey.split(',') : [];
    if (tickers.length === 0) return;
    setLoading(true);
    fetchTickerSummaries(tickers)
      .then(setSummaries)
      .finally(() => setLoading(false));
  }, [tickerKey]);

  useRegisterRefresh('watchlist-summaries', fetchAll);

  // Sync "dividend" tag on watchlist items when summary data is available (re-checked on each load/refresh)
  useEffect(() => {
    const dividendTag = 'dividend';
    for (const item of items) {
      if (item.id == null) continue;
      const s = summaries.get(item.ticker);
      const hasDividend = !!(s && (s.dividendYield > 0 || s.dividendRate > 0));
      const hasTag = item.tags.includes(dividendTag);
      if (hasDividend && !hasTag) {
        updateWatchlistItem(item.id, { tags: [...item.tags, dividendTag] });
      } else if (!hasDividend && hasTag) {
        updateWatchlistItem(item.id, {
          tags: item.tags.filter((t) => t !== dividendTag),
        });
      }
    }
  }, [items, summaries]);

  // Sync recommendation tag on watchlist items when summary data is available (re-checked on each load/refresh)
  useEffect(() => {
    for (const item of items) {
      if (item.id == null) continue;
      const s = summaries.get(item.ticker);
      const wantedTag = s?.recommendation ? normalizeRecommendationKey(s.recommendation) : null;
      const hasRecTag = RECOMMENDATION_TAGS.some((t) => item.tags.includes(t));
      if (wantedTag) {
        const otherRecTags = item.tags.filter((t) => isRecommendationTag(t));
        if (!otherRecTags.includes(wantedTag) || otherRecTags.length > 1) {
          const withoutRec = item.tags.filter((t) => !isRecommendationTag(t));
          updateWatchlistItem(item.id, { tags: [...withoutRec, wantedTag] });
        }
      } else if (hasRecTag) {
        updateWatchlistItem(item.id, {
          tags: item.tags.filter((t) => !isRecommendationTag(t)),
        });
      }
    }
  }, [items, summaries]);

  const filtered = useMemo(
    () =>
      activeTag ? items.filter((w) => w.tags.includes(activeTag)) : items,
    [items, activeTag]
  );

  // Tag filter order: portfolio, dividend, then recommendations (strong_buy → strong_sell), then any other tags
  const sortedTags = useMemo(() => {
    const set = new Set(allTags);
    const result: string[] = [];
    if (set.has('portfolio')) {
      result.push('portfolio');
      set.delete('portfolio');
    }
    if (set.has('dividend')) {
      result.push('dividend');
      set.delete('dividend');
    }
    for (const t of RECOMMENDATION_TAGS) {
      if (set.has(t)) {
        result.push(t);
        set.delete(t);
      }
    }
    result.push(...set);
    return result;
  }, [allTags]);

  const sorted = useMemo(() => {
    const getVal = (item: typeof filtered[0]) => {
      const s = summaries.get(item.ticker);
      const iv = latestIVs.get(item.ticker)?.value;
      const target = s?.targetMedian ?? 0;
      const price = s?.price ?? 0;
      const changePct = price > 0 ? (s?.changePercent ?? 0) : 0;
      const ivUpside = iv && price > 0 ? ((iv - price) / price) * 100 : -Infinity;
      const targetUpside = target > 0 && price > 0 ? ((target - price) / price) * 100 : -Infinity;
      const candidates = [iv, target].filter((v): v is number => v != null && v > 0);
      const minVal = candidates.length > 0 ? Math.min(...candidates) : 0;
      const minUpside = minVal > 0 && price > 0 ? ((minVal - price) / price) * 100 : -Infinity;

      switch (sortCol) {
        case 'ticker': return 0;
        case 'price': return price;
        case 'change': return changePct;
        case 'intrinsic': return ivUpside;
        case 'target': return targetUpside;
        case 'min': return minUpside;
        case 'dividend': return s?.dividendYield ?? -Infinity;
      }
    };

    const arr = [...filtered];
    if (sortCol === 'ticker') {
      arr.sort((a, b) => sortDir === 'asc'
        ? a.ticker.localeCompare(b.ticker)
        : b.ticker.localeCompare(a.ticker));
    } else {
      arr.sort((a, b) => {
        const va = getVal(a);
        const vb = getVal(b);
        return sortDir === 'asc' ? va - vb : vb - va;
      });
    }
    return arr;
  }, [filtered, summaries, latestIVs, sortCol, sortDir]);

  function toggleSort(col: typeof sortCol) {
    if (sortCol === col) {
      setSortDir((d) => (d === 'asc' ? 'desc' : 'asc'));
    } else {
      setSortCol(col);
      setSortDir(col === 'ticker' ? 'asc' : 'desc');
    }
  }

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <h1 className="text-2xl font-bold text-gray-900 dark:text-white">
            Watchlist
          </h1>
          <MarketBadge state={marketState} />
        </div>
        <div className="flex items-center gap-2">
          <RefreshButton />
          <button
            onClick={() => setShowAdd(true)}
            className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 transition-colors"
          >
            <Plus size={14} />
            Add Ticker
          </button>
        </div>
      </div>

      {sortedTags.length > 0 && (
        <div className="flex flex-wrap gap-1.5 mb-5">
          <button
            onClick={() => setActiveTag(null)}
            className={cn(
              'px-2.5 py-1 text-xs font-medium rounded-full transition-colors',
              activeTag === null
                ? 'bg-indigo-600 text-white'
                : 'bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-400 hover:bg-gray-200 dark:hover:bg-slate-700'
            )}
          >
            All
          </button>
          {sortedTags.map((tag) => {
            const isRec = isRecommendationTag(tag);
            const label = isRec ? formatRecommendation(tag) : tag;
            return (
              <button
                key={tag}
                onClick={() => setActiveTag(tag === activeTag ? null : tag)}
                className={cn(
                  'px-2.5 py-1 text-xs font-medium rounded-full transition-colors',
                  tag === activeTag
                    ? 'bg-indigo-600 text-white'
                    : tag === 'portfolio'
                      ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 hover:bg-emerald-200 dark:hover:bg-emerald-900/50'
                      : tag === 'dividend'
                        ? 'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 hover:bg-amber-200 dark:hover:bg-amber-900/50'
                        : isRec
                          ? tag === 'strong_buy' || tag === 'buy'
                            ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 hover:bg-emerald-200 dark:hover:bg-emerald-900/50'
                            : tag === 'strong_sell' || tag === 'sell'
                              ? 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400 hover:bg-red-200 dark:hover:bg-red-900/50'
                              : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200 dark:hover:bg-slate-700'
                          : 'bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-400 hover:bg-gray-200 dark:hover:bg-slate-700'
                )}
              >
                {label}
              </button>
            );
          })}
        </div>
      )}

      {showAdd && (
        <AddTickerForm
          onDone={() => setShowAdd(false)}
          existingTickers={items.map((w) => w.ticker)}
        />
      )}

      {sorted.length === 0 ? (
        <EmptyState
          icon={<Eye size={48} />}
          title="Watchlist is empty"
          description={
            activeTag
              ? `No items tagged "${activeTag}".`
              : 'Add tickers to start watching.'
          }
        />
      ) : (
        <div className="bg-white dark:bg-slate-900 rounded-xl border border-gray-200 dark:border-slate-800 overflow-hidden">
          <div className="grid grid-cols-[1fr_90px_90px_90px_90px_90px_70px_70px_130px_70px] gap-2 px-4 py-2.5 text-xs font-medium text-gray-500 dark:text-slate-400 border-b border-gray-100 dark:border-slate-800">
            <SortHeader label="Ticker" col="ticker" current={sortCol} dir={sortDir} onSort={toggleSort} />
            <SortHeader label="Price" col="price" current={sortCol} dir={sortDir} onSort={toggleSort} align="right" />
            <SortHeader label="Change" col="change" current={sortCol} dir={sortDir} onSort={toggleSort} align="right" />
            <SortHeader label="Intrinsic" col="intrinsic" current={sortCol} dir={sortDir} onSort={toggleSort} align="right" />
            <SortHeader label="Target" col="target" current={sortCol} dir={sortDir} onSort={toggleSort} align="right" />
            <SortHeader label="Min(IV, T)" col="min" current={sortCol} dir={sortDir} onSort={toggleSort} align="right" />
            <SortHeader label="Div" col="dividend" current={sortCol} dir={sortDir} onSort={toggleSort} align="right" />
            <span className="text-right">Rec</span>
            <span className="text-center">52w Range</span>
            <span />
          </div>

          {sorted.map((item) => (
            <WatchlistRow
              key={item.id}
              item={item}
              summary={summaries.get(item.ticker)}
              latestIV={latestIVs.get(item.ticker)}
              loading={loading}
              onRowClick={() => setChartTicker(item.ticker)}
            />
          ))}
        </div>
      )}

      {chartTicker && (
        <TickerDetailModal
          ticker={chartTicker}
          summary={summaries.get(chartTicker)}
          onClose={() => setChartTicker(null)}
        />
      )}
    </div>
  );
}

// --------------- Sort Header ---------------

type SortCol = 'ticker' | 'price' | 'change' | 'intrinsic' | 'target' | 'min' | 'dividend';

function SortHeader({
  label,
  col,
  current,
  dir,
  onSort,
  align,
}: {
  label: string;
  col: SortCol;
  current: SortCol;
  dir: 'asc' | 'desc';
  onSort: (col: SortCol) => void;
  align?: 'right';
}) {
  const active = current === col;
  return (
    <button
      onClick={() => onSort(col)}
      className={cn(
        'flex items-center gap-0.5 transition-colors hover:text-gray-700 dark:hover:text-slate-200',
        align === 'right' && 'justify-end',
        active && 'text-indigo-600 dark:text-indigo-400'
      )}
    >
      {label}
      {active && (dir === 'asc' ? <ArrowUp size={10} /> : <ArrowDown size={10} />)}
    </button>
  );
}

// --------------- Watchlist Row ---------------

function WatchlistRow({
  item,
  summary,
  latestIV,
  loading,
  onRowClick,
}: {
  item: { id?: number; ticker: string; name: string; tags: string[] };
  summary: TickerSummary | undefined;
  latestIV: IntrinsicValue | undefined;
  loading: boolean;
  onRowClick: () => void;
}) {
  const { extendedHours } = useExtendedHours();
  const [showTagEditor, setShowTagEditor] = useState(false);
  const [showIVInput, setShowIVInput] = useState(false);
  const [ivInput, setIvInput] = useState('');
  const [tagInput, setTagInput] = useState('');
  const isPortfolio = item.tags.includes('portfolio');

  const hasExt = extendedHours && summary?.extPrice != null;
  const price = hasExt ? summary!.extPrice! : (summary?.price ?? 0);
  const change = hasExt ? (summary!.extChange ?? 0) : (summary?.change ?? 0);
  const changePct = hasExt
    ? (summary!.extChangePercent ?? 0)
    : (summary?.changePercent ?? 0);
  const lo = summary?.fiftyTwoWeekLow ?? 0;
  const hi = summary?.fiftyTwoWeekHigh ?? 0;
  const range = hi - lo;
  const positionPct = range > 0 ? ((price - lo) / range) * 100 : 50;

  const ivValue = latestIV?.value;
  const ivUpside =
    ivValue && price > 0 ? ((ivValue - price) / price) * 100 : undefined;

  const targetMedian = summary?.targetMedian ?? 0;
  const targetUpside =
    targetMedian > 0 && price > 0
      ? ((targetMedian - price) / price) * 100
      : undefined;

  const candidates = [ivValue, targetMedian].filter((v): v is number => v != null && v > 0);
  const minValue = candidates.length > 0 ? Math.min(...candidates) : undefined;
  const minUpside =
    minValue != null && price > 0 ? ((minValue - price) / price) * 100 : undefined;

  async function handleAddIV(e: React.FormEvent) {
    e.preventDefault();
    const val = parseFloat(ivInput);
    if (isNaN(val) || val <= 0) return;
    await addIntrinsicValue(item.ticker, val);
    setIvInput('');
    setShowIVInput(false);
  }

  function handleTagKeyDown(e: React.KeyboardEvent) {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault();
      const tag = tagInput.trim().toLowerCase();
      if (tag && !item.tags.includes(tag) && item.id) {
        updateWatchlistItem(item.id, { tags: [...item.tags, tag] });
      }
      setTagInput('');
    }
  }

  function removeTag(tag: string) {
    if (tag === 'portfolio' || tag === 'dividend' || isRecommendationTag(tag) || !item.id) return;
    updateWatchlistItem(item.id, {
      tags: item.tags.filter((t) => t !== tag),
    });
  }

  function stopProp(e: React.MouseEvent) {
    e.stopPropagation();
  }

  return (
    <div className="border-b border-gray-50 dark:border-slate-800/50 last:border-b-0">
      <div
        className="grid grid-cols-[1fr_90px_90px_90px_90px_90px_70px_70px_130px_70px] gap-2 px-4 py-3 items-center cursor-pointer hover:bg-gray-50/70 dark:hover:bg-slate-800/30 transition-colors"
        onClick={onRowClick}
      >
        {/* Ticker + name + tags */}
        <div className="min-w-0">
          <div className="flex items-center gap-2">
            <span className="text-sm font-semibold text-gray-900 dark:text-white">
              {item.ticker}
            </span>
            <span className="text-xs text-gray-500 dark:text-slate-400 truncate">
              {summary?.name ?? item.name}
            </span>
          </div>
          <div className="flex items-center gap-1 mt-1 flex-wrap">
            {[...item.tags].sort((a, b) => a.localeCompare(b)).map((tag) => (
              <span
                key={tag}
                className={cn(
                  'text-[10px] font-medium px-1.5 py-0.5 rounded-full',
                  tag === 'portfolio'
                    ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400'
                    : tag === 'dividend'
                      ? 'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400'
                      : isRecommendationTag(tag)
                        ? tag === 'strong_buy' || tag === 'buy'
                          ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400'
                          : tag === 'strong_sell' || tag === 'sell'
                            ? 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400'
                            : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
                        : 'bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-400'
                )}
              >
                {isRecommendationTag(tag) ? formatRecommendation(tag) : tag}
              </span>
            ))}
          </div>
        </div>

        {/* Price */}
        <span
          className={cn(
            'text-sm font-medium tabular-nums text-right',
            loading ? 'animate-pulse' : '',
            'text-gray-900 dark:text-white'
          )}
        >
          {price > 0 ? (
            <>
              {formatCurrency(price)}
              {hasExt && (
                <span className="ml-0.5 text-[9px] text-amber-500 align-super">
                  EXT
                </span>
              )}
            </>
          ) : '—'}
        </span>

        {/* Change */}
        <div className="text-right">
          {price > 0 ? (
            <>
              <p
                className={cn(
                  'text-xs font-medium tabular-nums',
                  change >= 0 ? 'text-gain' : 'text-loss'
                )}
              >
                {change >= 0 ? '+' : ''}
                {formatCurrency(change)}
              </p>
              <p
                className={cn(
                  'text-[10px] tabular-nums',
                  change >= 0 ? 'text-gain' : 'text-loss'
                )}
              >
                {change >= 0 ? '+' : ''}
                {changePct.toFixed(2)}%
              </p>
            </>
          ) : (
            <span className="text-sm text-gray-400">—</span>
          )}
        </div>

        {/* Intrinsic value + upside (upside primary) */}
        <div className="text-right">
          {ivValue != null ? (
            <>
              {ivUpside != null ? (
                <p
                  className={cn(
                    'text-sm font-medium tabular-nums',
                    ivUpside > 0 ? 'text-gain' : 'text-loss'
                  )}
                  title="Potential upside from current price"
                >
                  {ivUpside > 0 ? '+' : ''}
                  {ivUpside.toFixed(1)}%
                </p>
              ) : (
                <p className="text-sm font-medium tabular-nums text-gray-500 dark:text-slate-400">—</p>
              )}
              <p className="text-[10px] tabular-nums text-gray-500 dark:text-slate-400">
                {formatCurrency(ivValue)}
              </p>
            </>
          ) : (
            <button
              onClick={(e) => { stopProp(e); setShowIVInput(true); }}
              className="text-[10px] text-gray-400 hover:text-indigo-500 transition-colors ml-auto block"
            >
              + set
            </button>
          )}
        </div>

        {/* Analyst median target + upside (upside primary) */}
        <div className="text-right">
          {targetMedian > 0 ? (
            <>
              {targetUpside != null ? (
                <p
                  className={cn(
                    'text-sm font-medium tabular-nums',
                    targetUpside > 0 ? 'text-gain' : 'text-loss'
                  )}
                  title="Analyst upside to median target"
                >
                  {targetUpside > 0 ? '+' : ''}
                  {targetUpside.toFixed(1)}%
                </p>
              ) : (
                <p className="text-sm font-medium tabular-nums text-gray-500 dark:text-slate-400">—</p>
              )}
              <p className="text-[10px] tabular-nums text-gray-500 dark:text-slate-400">
                {formatCurrency(targetMedian)}
              </p>
            </>
          ) : (
            <span className="text-xs text-gray-400">—</span>
          )}
        </div>

        {/* Min of intrinsic & target (upside primary) */}
        <div className="text-right">
          {minValue != null ? (
            <>
              {minUpside != null ? (
                <p
                  className={cn(
                    'text-sm font-bold tabular-nums',
                    minUpside > 0 ? 'text-gain' : 'text-loss'
                  )}
                  title="Upside to min of intrinsic & target"
                >
                  {minUpside > 0 ? '+' : ''}
                  {minUpside.toFixed(1)}%
                </p>
              ) : (
                <p className="text-sm font-bold tabular-nums text-gray-500 dark:text-slate-400">—</p>
              )}
              <p className="text-[10px] tabular-nums text-gray-500 dark:text-slate-400">
                {formatCurrency(minValue)}
              </p>
            </>
          ) : (
            <span className="text-xs text-gray-400">—</span>
          )}
        </div>

        {/* Dividend */}
        <div className="text-right text-sm tabular-nums text-gray-700 dark:text-slate-300">
          {summary && (summary.dividendYield > 0 || summary.dividendRate > 0) ? (
            <span title={summary.dividendRate > 0 ? formatCurrency(summary.dividendRate) + '/yr' : ''}>
              {summary.dividendYield > 0 ? `${summary.dividendYield.toFixed(2)}%` : formatCurrency(summary.dividendRate)}
            </span>
          ) : (
            '—'
          )}
        </div>

        {/* Analyst recommendation */}
        <div className="text-right">
          {summary?.recommendation ? (
            <span
              className={cn(
                'text-[10px] font-medium px-1.5 py-0.5 rounded uppercase',
                summary.recommendation === 'strong_buy' || summary.recommendation === 'buy'
                  ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400'
                  : summary.recommendation === 'strong_sell' || summary.recommendation === 'sell'
                    ? 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400'
                    : 'bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-400'
              )}
            >
              {formatRecommendation(summary.recommendation)}
            </span>
          ) : (
            <span className="text-xs text-gray-400">—</span>
          )}
        </div>

        {/* 52w range */}
        <div className="flex flex-col items-center gap-1">
          {lo > 0 && hi > 0 ? (
            <>
              <div className="w-full flex justify-between text-[10px] tabular-nums text-gray-500 dark:text-slate-400">
                <span>{formatCurrency(lo)}</span>
                <span>{formatCurrency(hi)}</span>
              </div>
              <div className="w-full h-1.5 rounded-full bg-gray-100 dark:bg-slate-800 relative">
                <div
                  className="absolute top-0 h-full rounded-full bg-gradient-to-r from-red-400 via-yellow-400 to-emerald-400 opacity-40"
                  style={{ width: '100%' }}
                />
                <div
                  className="absolute top-1/2 -translate-y-1/2 w-2.5 h-2.5 rounded-full bg-indigo-500 border-2 border-white dark:border-slate-900 shadow-sm"
                  style={{
                    left: `calc(${Math.min(Math.max(positionPct, 2), 98)}% - 5px)`,
                  }}
                />
              </div>
            </>
          ) : (
            <span className="text-xs text-gray-400">—</span>
          )}
        </div>

        {/* Actions */}
        <div className="flex items-center justify-end gap-0.5" onClick={stopProp}>
          <button
            onClick={() => setShowIVInput(!showIVInput)}
            className="p-1 rounded text-gray-400 hover:text-amber-500 hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors"
            title="Set intrinsic value"
          >
            <Target size={14} />
          </button>
          <button
            onClick={onRowClick}
            className="p-1 rounded text-gray-400 hover:text-indigo-500 hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors"
            title="Price vs Intrinsic chart"
          >
            <LineChart size={14} />
          </button>
          <button
            onClick={() => setShowTagEditor(!showTagEditor)}
            className="p-1 rounded text-gray-400 hover:text-indigo-500 hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors"
            title="Edit tags"
          >
            <Tag size={14} />
          </button>
          {!isPortfolio && (
            <button
              onClick={() => item.id && deleteWatchlistItem(item.id)}
              className="p-1 rounded text-gray-400 hover:text-red-500 hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors"
              title="Remove"
            >
              <Trash2 size={14} />
            </button>
          )}
        </div>
      </div>

      {/* Inline IV input */}
      {showIVInput && (
        <form
          onSubmit={handleAddIV}
          className="px-4 pb-3 flex items-center gap-2"
          onClick={stopProp}
        >
          <span className="text-xs text-gray-500 dark:text-slate-400 shrink-0">
            Intrinsic value:
          </span>
          <input
            type="number"
            step="any"
            min="0"
            value={ivInput}
            onChange={(e) => setIvInput(e.target.value)}
            placeholder={ivValue?.toString() ?? '0.00'}
            autoFocus
            className="px-2 py-1 text-xs rounded bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-900 dark:text-white outline-none focus:ring-1 focus:ring-indigo-500 w-28 tabular-nums"
          />
          <button
            type="submit"
            className="px-2 py-1 text-xs font-medium rounded bg-indigo-600 text-white hover:bg-indigo-700 transition-colors"
          >
            Save
          </button>
          <button
            type="button"
            onClick={() => setShowIVInput(false)}
            className="px-2 py-1 text-xs text-gray-500 hover:text-gray-700 dark:hover:text-slate-300"
          >
            Cancel
          </button>
        </form>
      )}

      {/* Inline tag editor */}
      {showTagEditor && (
        <div className="px-4 pb-3 flex items-center gap-2 flex-wrap" onClick={stopProp}>
          {[...item.tags].sort((a, b) => a.localeCompare(b)).map((tag) => (
            <span
              key={tag}
              className={cn(
                'inline-flex items-center gap-1 px-2 py-0.5 text-xs font-medium rounded-full',
                tag === 'portfolio'
                  ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-300'
                  : tag === 'dividend'
                    ? 'bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-300'
                    : 'bg-indigo-100 dark:bg-indigo-900/30 text-indigo-700 dark:text-indigo-300'
              )}
            >
              {isRecommendationTag(tag) ? formatRecommendation(tag) : tag}
              {tag !== 'portfolio' && tag !== 'dividend' && !isRecommendationTag(tag) && (
                <button
                  onClick={() => removeTag(tag)}
                  className="hover:text-red-500"
                >
                  <X size={10} />
                </button>
              )}
            </span>
          ))}
          <input
            type="text"
            value={tagInput}
            onChange={(e) => setTagInput(e.target.value)}
            onKeyDown={handleTagKeyDown}
            placeholder="Add tag…"
            className="px-2 py-0.5 text-xs rounded bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-slate-500 outline-none focus:ring-1 focus:ring-indigo-500 w-24"
          />
        </div>
      )}
    </div>
  );
}

// --------------- Ticker Detail Modal (Chart + Financials) ---------------

const CHART_RANGE_PRESETS: { value: ChartRange; label: string }[] = [
  { value: '10y', label: '10Y' },
  { value: '5y', label: '5Y' },
  { value: '1y', label: '1Y' },
  { value: '6mo', label: '6M' },
  { value: '3mo', label: '3M' },
  { value: '1d', label: '1D' },
  { value: 'max', label: 'Max' },
];

const RANGE_DAYS: Record<Exclude<ChartRange, 'max'>, number> = {
  '1d': 1,
  '3mo': 90,
  '6mo': 180,
  '1y': 365,
  '2y': 730,
  '5y': 1825,
  '10y': 3650,
};

function TickerDetailModal({
  ticker,
  summary,
  onClose,
}: {
  ticker: string;
  summary: TickerSummary | undefined;
  onClose: () => void;
}) {
  const ivHistory = useIntrinsicValues(ticker);
  const [historicalPrices, setHistoricalPrices] = useState<HistoricalPrice[]>([]);
  const [loadingPrices, setLoadingPrices] = useState(false);
  const [chartRange, setChartRange] = useState<ChartRange | 'custom'>('1y');
  const [dataSpanDays, setDataSpanDays] = useState<number | null>(null);
  const [customFrom, setCustomFrom] = useState(() => {
    const d = new Date();
    d.setMonth(d.getMonth() - 6);
    return d.toISOString().slice(0, 10);
  });
  const [customTo, setCustomTo] = useState(() => new Date().toISOString().slice(0, 10));
  const [ivInput, setIvInput] = useState('');
  const [ivDateInput, setIvDateInput] = useState(() => new Date().toISOString().slice(0, 10));
  const [activeTab, setActiveTab] = useState<'chart' | 'financials' | 'notes'>('chart');
  const tickerNotes = useNotes(undefined, ticker);

  const fetchRange = chartRange === 'custom' ? '10y' : chartRange;

  useEffect(() => {
    setLoadingPrices(true);
    fetchHistoricalPrices(ticker, fetchRange)
      .then(setHistoricalPrices)
      .finally(() => setLoadingPrices(false));
  }, [ticker, fetchRange]);

  // Fetch max range once per ticker to know available data span; hide range toggles that don't apply
  useEffect(() => {
    setDataSpanDays(null);
    fetchHistoricalPrices(ticker, 'max').then((prices) => {
      if (prices.length >= 2) {
        const min = Math.min(...prices.map((p) => p.date));
        const max = Math.max(...prices.map((p) => p.date));
        setDataSpanDays((max - min) / (24 * 3600));
      }
    });
  }, [ticker]);

  const visibleRangePresets = useMemo(() => {
    if (dataSpanDays == null) return CHART_RANGE_PRESETS;
    return CHART_RANGE_PRESETS.filter((p) => {
      if (p.value === 'max') return true;
      if (p.value === '1d') return true;
      const days = RANGE_DAYS[p.value as keyof typeof RANGE_DAYS];
      return days <= dataSpanDays;
    });
  }, [dataSpanDays]);

  const targetMedian = summary?.targetMedian ?? 0;
  const currentPrice = summary?.price ?? 0;

  const chartData = useMemo(() => {
    let prices = historicalPrices;
    if (chartRange === 'custom' && customFrom && customTo) {
      const fromTs = new Date(customFrom + 'T00:00:00').getTime() / 1000;
      const toTs = new Date(customTo + 'T23:59:59').getTime() / 1000;
      prices = historicalPrices.filter((hp) => hp.date >= fromTs && hp.date <= toTs);
    }
    if (prices.length === 0) return [];

    const ivByDate = new Map<string, number>();

    const sortedIV = [...ivHistory].sort(
      (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
    );
    for (const iv of sortedIV) {
      const key = new Date(iv.date).toISOString().slice(0, 10);
      ivByDate.set(key, iv.value);
    }

    // Start with the earliest IV value so the line extends to the beginning
    let lastIV: number | null = sortedIV.length > 0 ? sortedIV[0].value : null;

    const ivDates = sortedIV.map((iv) => ({
      ts: new Date(iv.date).getTime(),
      value: iv.value,
    }));

    return prices.map((hp) => {
      const d = new Date(hp.date * 1000);
      const dateStr = d.toISOString().slice(0, 10);
      const ts = d.getTime();

      if (ivByDate.has(dateStr)) {
        lastIV = ivByDate.get(dateStr)!;
      } else {
        for (const iv of ivDates) {
          if (iv.ts <= ts) lastIV = iv.value;
          else break;
        }
      }

      return {
        date: chartRange === '1d' ? d.toISOString() : dateStr,
        price: Math.round(hp.close * 100) / 100,
        intrinsic: lastIV,
        target: targetMedian > 0 ? targetMedian : null,
      };
    });
  }, [historicalPrices, ivHistory, targetMedian, chartRange, customFrom, customTo]);

  async function handleAddIV(e: React.FormEvent) {
    e.preventDefault();
    const val = parseFloat(ivInput);
    if (isNaN(val) || val <= 0) return;
    const date = ivDateInput ? new Date(ivDateInput + 'T12:00:00') : new Date();
    await addIntrinsicValue(ticker, val, date);
    setIvInput('');
    setIvDateInput(new Date().toISOString().slice(0, 10));
  }

  const latestIV = ivHistory.length > 0 ? ivHistory[ivHistory.length - 1] : null;

  return (
    <Modal open wide onClose={onClose} title={`${ticker} — ${summary?.name ?? ''}`}>
      <div className="space-y-4">
        {/* Tab switcher */}
        <div className="flex gap-1 border-b border-gray-200 dark:border-slate-700">
          <button
            onClick={() => setActiveTab('chart')}
            className={cn(
              'px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-px',
              activeTab === 'chart'
                ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400'
                : 'border-transparent text-gray-500 dark:text-slate-400 hover:text-gray-700 dark:hover:text-slate-300'
            )}
          >
            Price &amp; Intrinsic Value
          </button>
          <button
            onClick={() => setActiveTab('financials')}
            className={cn(
              'px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-px',
              activeTab === 'financials'
                ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400'
                : 'border-transparent text-gray-500 dark:text-slate-400 hover:text-gray-700 dark:hover:text-slate-300'
            )}
          >
            Financial Details
          </button>
          <button
            onClick={() => setActiveTab('notes')}
            className={cn(
              'px-4 py-2 text-sm font-medium border-b-2 transition-colors -mb-px',
              activeTab === 'notes'
                ? 'border-indigo-500 text-indigo-600 dark:text-indigo-400'
                : 'border-transparent text-gray-500 dark:text-slate-400 hover:text-gray-700 dark:hover:text-slate-300'
            )}
          >
            Research Notes
            {tickerNotes.length > 0 && (
              <span className="ml-1.5 inline-flex items-center justify-center w-4 h-4 text-[10px] font-bold rounded-full bg-indigo-100 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400">
                {tickerNotes.length}
              </span>
            )}
          </button>
        </div>

        {activeTab === 'chart' && (
          <div className="space-y-4">
            {/* Value summary cards */}
            <div className="grid grid-cols-3 gap-3">
              <div className="rounded-lg bg-indigo-50 dark:bg-indigo-900/20 border border-indigo-200 dark:border-indigo-800/40 p-3">
                <p className="text-[10px] font-medium text-indigo-500 dark:text-indigo-400 uppercase tracking-wider mb-0.5">
                  Market Price
                </p>
                <p className="text-lg font-bold text-indigo-700 dark:text-indigo-300 tabular-nums">
                  {currentPrice > 0 ? formatCurrency(currentPrice) : '—'}
                </p>
              </div>
              <div className="rounded-lg bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800/40 p-3">
                <p className="text-[10px] font-medium text-amber-500 dark:text-amber-400 uppercase tracking-wider mb-0.5">
                  Intrinsic Value
                </p>
                <p className="text-lg font-bold text-amber-700 dark:text-amber-300 tabular-nums">
                  {latestIV ? formatCurrency(latestIV.value) : '—'}
                </p>
                {latestIV && currentPrice > 0 && (
                  <p className={cn(
                    'text-xs font-medium tabular-nums',
                    latestIV.value > currentPrice ? 'text-gain' : 'text-loss'
                  )}>
                    {latestIV.value > currentPrice ? '+' : ''}
                    {(((latestIV.value - currentPrice) / currentPrice) * 100).toFixed(1)}% upside
                  </p>
                )}
              </div>
              <div className="rounded-lg bg-cyan-50 dark:bg-cyan-900/20 border border-cyan-200 dark:border-cyan-800/40 p-3">
                <p className="text-[10px] font-medium text-cyan-500 dark:text-cyan-400 uppercase tracking-wider mb-0.5">
                  Analyst Target
                </p>
                <p className="text-lg font-bold text-cyan-700 dark:text-cyan-300 tabular-nums">
                  {targetMedian > 0 ? formatCurrency(targetMedian) : '—'}
                </p>
                {targetMedian > 0 && currentPrice > 0 && (
                  <p className={cn(
                    'text-xs font-medium tabular-nums',
                    targetMedian > currentPrice ? 'text-gain' : 'text-loss'
                  )}>
                    {targetMedian > currentPrice ? '+' : ''}
                    {(((targetMedian - currentPrice) / currentPrice) * 100).toFixed(1)}% upside
                  </p>
                )}
              </div>
            </div>

            {/* Analyst recommendation on chart tab */}
            {summary?.recommendation && (
              <div className="flex items-center gap-2">
                <span className="text-xs text-gray-500 dark:text-slate-400">
                  Analyst recommendation:
                </span>
                <span
                  className={cn(
                    'text-xs font-semibold px-2 py-1 rounded uppercase',
                    summary.recommendation === 'strong_buy' || summary.recommendation === 'buy'
                      ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400'
                      : summary.recommendation === 'strong_sell' || summary.recommendation === 'sell'
                        ? 'bg-red-100 dark:bg-red-900/30 text-red-700 dark:text-red-400'
                        : 'bg-gray-100 dark:bg-slate-800 text-gray-700 dark:text-slate-300'
                  )}
                >
                  {formatRecommendation(summary.recommendation)}
                </span>
              </div>
            )}

            {/* Chart range selector */}
            <div className="flex flex-wrap items-center gap-2">
              <span className="text-xs text-gray-500 dark:text-slate-400">Range:</span>
              {visibleRangePresets.map(({ value, label }) => (
                <button
                  key={value}
                  type="button"
                  onClick={() => setChartRange(value)}
                  className={cn(
                    'px-2.5 py-1 text-xs font-medium rounded-lg border transition-colors',
                    chartRange === value
                      ? 'bg-indigo-600 border-indigo-600 text-white'
                      : 'border-gray-200 dark:border-slate-700 text-gray-600 dark:text-slate-400 hover:bg-gray-100 dark:hover:bg-slate-800'
                  )}
                >
                  {label}
                </button>
              ))}
              <button
                type="button"
                onClick={() => setChartRange('custom')}
                className={cn(
                  'px-2.5 py-1 text-xs font-medium rounded-lg border transition-colors',
                  chartRange === 'custom'
                    ? 'bg-indigo-600 border-indigo-600 text-white'
                    : 'border-gray-200 dark:border-slate-700 text-gray-600 dark:text-slate-400 hover:bg-gray-100 dark:hover:bg-slate-800'
                )}
              >
                Custom
              </button>
              {chartRange === 'custom' && (
                <div className="flex items-center gap-2 flex-wrap">
                  <input
                    type="date"
                    value={customFrom}
                    onChange={(e) => setCustomFrom(e.target.value)}
                    className="px-2 py-1 text-xs rounded-lg bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-900 dark:text-white"
                  />
                  <span className="text-xs text-gray-400">to</span>
                  <input
                    type="date"
                    value={customTo}
                    onChange={(e) => setCustomTo(e.target.value)}
                    className="px-2 py-1 text-xs rounded-lg bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-900 dark:text-white"
                  />
                </div>
              )}
            </div>

            {/* Add new IV */}
            <form onSubmit={handleAddIV} className="flex items-center gap-2 flex-wrap">
              <span className="text-xs text-gray-500 dark:text-slate-400 shrink-0">
                New intrinsic value:
              </span>
              <input
                type="number"
                step="any"
                min="0"
                value={ivInput}
                onChange={(e) => setIvInput(e.target.value)}
                placeholder={latestIV?.value.toString() ?? '0.00'}
                className="px-2 py-1.5 text-sm rounded-lg bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-900 dark:text-white outline-none focus:ring-1 focus:ring-indigo-500 w-28 tabular-nums"
              />
              <input
                type="date"
                value={ivDateInput}
                onChange={(e) => setIvDateInput(e.target.value)}
                className="px-2 py-1.5 text-sm rounded-lg bg-gray-50 dark:bg-slate-800 border border-gray-200 dark:border-slate-700 text-gray-900 dark:text-white outline-none focus:ring-1 focus:ring-indigo-500 tabular-nums"
              />
              <button
                type="submit"
                className="px-3 py-1.5 text-xs font-medium rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 transition-colors"
              >
                Add
              </button>
            </form>

            {/* Chart */}
            {loadingPrices ? (
              <div className="h-64 flex items-center justify-center text-sm text-gray-400">
                Loading historical data…
              </div>
            ) : chartData.length > 0 ? (
              <ResponsiveContainer width="100%" height={320}>
                <ComposedChart data={chartData}>
                  <CartesianGrid
                    strokeDasharray="3 3"
                    stroke="#334155"
                    opacity={0.3}
                  />
                  <XAxis
                    dataKey="date"
                    tick={{ fontSize: 10, fill: '#94a3b8' }}
                    tickFormatter={(v: string) => {
                      const d = new Date(v);
                      if (chartRange === '1d' || (typeof v === 'string' && v.includes('T'))) {
                        return d.toLocaleTimeString(undefined, { hour: '2-digit', minute: '2-digit' });
                      }
                      return `${d.getMonth() + 1}/${String(d.getFullYear()).slice(2)}`;
                    }}
                    interval="preserveStartEnd"
                    minTickGap={50}
                  />
                  <YAxis
                    tick={{ fontSize: 10, fill: '#94a3b8' }}
                    domain={['auto', 'auto']}
                    tickFormatter={(v: number) => `$${v}`}
                    width={60}
                  />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: '#1e293b',
                      border: '1px solid #334155',
                      borderRadius: '0.5rem',
                      color: '#e2e8f0',
                      fontSize: '0.75rem',
                    }}
                    labelStyle={{ color: '#94a3b8', marginBottom: 4 }}
                    formatter={(value, name) => [
                      value != null ? formatCurrency(Number(value)) : '',
                      name === 'price'
                        ? 'Market Price'
                        : name === 'intrinsic'
                          ? 'Intrinsic Value'
                          : 'Analyst Target',
                    ]}
                  />
                  <Line
                    type="monotone"
                    dataKey="price"
                    stroke="#6366f1"
                    strokeWidth={2}
                    dot={false}
                    name="price"
                  />
                  <Line
                    type="stepAfter"
                    dataKey="intrinsic"
                    stroke="#f59e0b"
                    strokeWidth={2}
                    strokeDasharray="6 3"
                    dot={false}
                    connectNulls
                    name="intrinsic"
                  />
                  {targetMedian > 0 && (
                    <Line
                      type="monotone"
                      dataKey="target"
                      stroke="#06b6d4"
                      strokeWidth={1.5}
                      strokeDasharray="4 4"
                      dot={false}
                      connectNulls
                      name="target"
                    />
                  )}
                  {latestIV && (
                    <ReferenceLine
                      y={latestIV.value}
                      stroke="#f59e0b"
                      strokeDasharray="3 3"
                      strokeOpacity={0.5}
                      label={{
                        value: `IV: ${formatCurrency(latestIV.value)}`,
                        position: 'insideTopRight',
                        fill: '#f59e0b',
                        fontSize: 11,
                        fontWeight: 600,
                      }}
                    />
                  )}
                  {targetMedian > 0 && (
                    <ReferenceLine
                      y={targetMedian}
                      stroke="#06b6d4"
                      strokeDasharray="3 3"
                      strokeOpacity={0.5}
                      label={{
                        value: `Target: ${formatCurrency(targetMedian)}`,
                        position: 'insideTopLeft',
                        fill: '#06b6d4',
                        fontSize: 11,
                        fontWeight: 600,
                      }}
                    />
                  )}
                </ComposedChart>
              </ResponsiveContainer>
            ) : (
              <div className="h-64 flex items-center justify-center text-sm text-gray-400">
                No historical data available.
              </div>
            )}

            {/* Legend */}
            <div className="flex items-center gap-4 text-xs text-gray-500 dark:text-slate-400">
              <div className="flex items-center gap-1.5">
                <div className="w-4 h-0.5 bg-indigo-500 rounded" />
                Market Price
              </div>
              <div className="flex items-center gap-1.5">
                <div className="w-4 h-0.5 rounded" style={{ borderTop: '2px dashed #f59e0b', height: 0 }} />
                Intrinsic Value
              </div>
              <div className="flex items-center gap-1.5">
                <div className="w-4 h-0.5 rounded" style={{ borderTop: '2px dashed #06b6d4', height: 0 }} />
                Analyst Target
              </div>
            </div>

            {/* IV History */}
            {ivHistory.length > 0 && (
              <div>
                <h3 className="text-xs font-medium text-gray-500 dark:text-slate-400 mb-2">
                  Intrinsic Value History
                </h3>
                <div className="space-y-1 max-h-40 overflow-y-auto">
                  {[...ivHistory].reverse().map((iv) => (
                    <div
                      key={iv.id}
                      className="flex items-center justify-between py-1.5 px-2 rounded-md hover:bg-gray-50 dark:hover:bg-slate-800/30 group"
                    >
                      <div className="flex items-center gap-3">
                        <span className="text-xs text-gray-500 dark:text-slate-400 tabular-nums">
                          {new Date(iv.date).toLocaleDateString()}
                        </span>
                        <span className="text-sm font-medium text-gray-900 dark:text-white tabular-nums">
                          {formatCurrency(iv.value)}
                        </span>
                      </div>
                      <button
                        onClick={() => iv.id && deleteIntrinsicValue(iv.id)}
                        className="p-1 rounded text-gray-300 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"
                      >
                        <Trash2 size={12} />
                      </button>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {activeTab === 'financials' && (
          <TickerDetailView ticker={ticker} />
        )}

        {activeTab === 'notes' && (
          <div className="space-y-4">
            {tickerNotes.length === 0 ? (
              <div className="text-center py-12 text-gray-400 dark:text-slate-500">
                <p className="text-sm">No research notes linked to {ticker}.</p>
                <p className="text-xs mt-1">
                  Link this ticker in the Research tab to see notes here.
                </p>
              </div>
            ) : (
              tickerNotes.map((note) => (
                <div
                  key={note.id}
                  className="bg-white dark:bg-slate-900 rounded-xl border border-gray-200 dark:border-slate-800 p-5"
                >
                  <div className="flex items-start justify-between mb-3">
                    <h3 className="text-base font-semibold text-gray-900 dark:text-white">
                      {note.title || 'Untitled'}
                    </h3>
                    <span className="text-[10px] text-gray-400 dark:text-slate-500 shrink-0 ml-3 tabular-nums">
                      {new Date(note.updatedAt).toLocaleDateString(undefined, {
                        year: 'numeric',
                        month: 'short',
                        day: 'numeric',
                      })}
                    </span>
                  </div>
                  {note.tags.length > 0 && (
                    <div className="flex flex-wrap gap-1 mb-3">
                      {note.tags.map((tag) => (
                        <span
                          key={tag}
                          className={cn(
                            'text-[10px] font-medium px-1.5 py-0.5 rounded-full',
                            note.tickerLinks.map((t) => t.toLowerCase()).includes(tag)
                              ? 'bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400'
                              : 'bg-gray-100 dark:bg-slate-800 text-gray-600 dark:text-slate-400'
                          )}
                        >
                          {tag}
                        </span>
                      ))}
                    </div>
                  )}
                  <div
                    className="tiptap text-sm text-gray-700 dark:text-slate-300"
                    dangerouslySetInnerHTML={{ __html: note.content }}
                  />
                </div>
              ))
            )}
          </div>
        )}
      </div>
    </Modal>
  );
}

// --------------- Add Ticker Form ---------------

function AddTickerForm({
  onDone,
  existingTickers,
}: {
  onDone: () => void;
  existingTickers: string[];
}) {
  const [ticker, setTicker] = useState('');
  const [lookupState, setLookupState] = useState<
    'idle' | 'loading' | 'found' | 'notfound'
  >('idle');
  const [name, setName] = useState('');
  const [tags, setTags] = useState('');
  const [tagError, setTagError] = useState<string | null>(null);
  const lookupTimeoutRef = useRef<number>(0);

  const existingTickersKey = existingTickers.join(',');
  useEffect(() => {
    const key = ticker.trim().toUpperCase();
    if (key.length < 1) {
      setLookupState('idle');
      return;
    }
    const existing = existingTickers.includes(key);
    if (existing) {
      setLookupState('notfound');
      setName('Already in watchlist');
      return;
    }
    setLookupState('loading');
    clearTimeout(lookupTimeoutRef.current);
    lookupTimeoutRef.current = window.setTimeout(async () => {
      const info = await lookupTicker(key);
      if (info) {
        setName(info.name);
        setLookupState('found');
      } else {
        setName('');
        setLookupState('notfound');
      }
    }, 400);
    return () => clearTimeout(lookupTimeoutRef.current);
  }, [ticker, existingTickersKey]);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setTagError(null);
    const key = ticker.trim().toUpperCase();
    if (!key || existingTickers.includes(key)) return;
    const parsed = tags
      .split(',')
      .map((t) => t.trim().toLowerCase())
      .filter(Boolean);
    const autoTags = parsed.filter((t) => isAutoGeneratedTag(t));
    if (autoTags.length > 0) {
      setTagError(
        `These tags are added automatically and cannot be set manually: ${autoTags.join(', ')}. Remove them and try again.`
      );
      return;
    }
    await addWatchlistItem({ ticker: key, name: name || key, tags: parsed });
    onDone();
  }

  const inputClass =
    'w-full px-3 py-2 rounded-lg bg-gray-50 dark:bg-slate-800 border border-gray-300 dark:border-slate-700 text-gray-900 dark:text-white placeholder-gray-400 dark:placeholder-slate-500 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-sm';

  return (
    <form
      onSubmit={handleSubmit}
      className="bg-white dark:bg-slate-900 rounded-xl border border-gray-200 dark:border-slate-800 p-4 mb-5"
    >
      <div className="grid sm:grid-cols-4 gap-3 items-start">
        <div className="sm:col-span-2 min-w-0">
          <label className="block text-xs font-medium text-gray-500 dark:text-slate-400 mb-1">
            Ticker
          </label>
          <TickerSearchInput
            value={ticker}
            onChange={(v) => setTicker(v.toUpperCase())}
            onSelect={(symbol, companyName) => {
              setTicker(symbol);
              setName(companyName);
            }}
            placeholder="Search by ticker or company name"
            allowSearch
            inputClass={inputClass}
            autoFocus
          />
          <div className="min-h-[1.25rem] mt-0.5">
            {name && lookupState !== 'notfound' && (
              <p className="text-[10px] text-emerald-600 dark:text-emerald-400 truncate">
                {lookupState === 'loading' ? `${name} (checking…)` : name}
              </p>
            )}
            {lookupState === 'notfound' && (
              <p className="text-[10px] text-red-500">
                {name || 'Ticker not found or already in watchlist'}
              </p>
            )}
          </div>
        </div>

        <div className="min-w-0">
          <label className="block text-xs font-medium text-gray-500 dark:text-slate-400 mb-1">
            Name
          </label>
          <input
            type="text"
            value={name}
            onChange={(e) => setName(e.target.value)}
            placeholder="Company name"
            className={inputClass}
          />
        </div>

        <div className="min-w-0">
          <label className="block text-xs font-medium text-gray-500 dark:text-slate-400 mb-1">
            Tags (comma-separated)
          </label>
          <input
            type="text"
            value={tags}
            onChange={(e) => {
              setTags(e.target.value);
              if (tagError) setTagError(null);
            }}
            placeholder="tech, growth"
            className={inputClass}
          />
          <div className="min-h-[1.25rem] mt-1" aria-live="polite">
            {tagError && (
              <p className="text-xs text-amber-600 dark:text-amber-400" role="alert">
                {tagError}
              </p>
            )}
          </div>
        </div>

        <div className="flex gap-2">
          <button
            type="submit"
            disabled={!ticker.trim() || lookupState === 'loading'}
            className="flex-1 px-3 py-2 text-sm font-medium rounded-lg bg-indigo-600 text-white hover:bg-indigo-700 transition-colors disabled:opacity-50"
          >
            Add
          </button>
          <button
            type="button"
            onClick={onDone}
            className="px-3 py-2 text-sm font-medium rounded-lg text-gray-600 dark:text-slate-400 hover:bg-gray-100 dark:hover:bg-slate-800 transition-colors"
          >
            Cancel
          </button>
        </div>
      </div>
    </form>
  );
}
